### ISSUE TITLE
Add users to an issuance by CSV upload

### ISSUE THREAD

**Issue by stuartf** [c21u/blockcerts-admin-app#20]
For large classes with a predefined roster we'll want to be able to upload a CSV instead of giving out the self-registration link.

**Comment by mlisle** [comment]
Reopening for now... I encountered an issue where I got intermittent 500 Server Error messages when trying to upload. There didn't seem to be any rhyme or reason to when it occurred. 

I tested with the same CSV file over the past hour and got mixed results... though the last few have been successful.

**Comment by stuartf** [comment]
I've documented the cause of the 500 error in #47
