### ISSUE TITLE
Need ability to revise existing credential

### ISSUE THREAD

**Issue by mlisle** [c21u/blockcerts-admin-app#32]
This came up while working with GTLI this morning on our pilot. We're trying to finalize the text for their blockcert. However, once I create it, I can't revise it. 

For now, I would suggest that we link the credential title on the "Manage Recipients" screen back to the editable form for that credential. 

If we do that, we should also rename this page to "Manage Credentials." I'm open to suggestions on how best to do this.

**Comment by stuartf** [comment]
The view and url already exist for this (`/credential/:id:`), we just need to link to it.
