### ISSUE TITLE
FInalize Completed Screen

### ISSUE THREAD

**Issue by mlisle** [c21u/blockcerts-admin-app#63]
Hood up Completed screen to db.

**Comment by mlisle** [comment]
There are a few remaining issues with the Completed screen. 

- Should appear on Completed once "Approved"
- Add column for "Approved Date"
- Change column from "Last Notified" to "Issue Date"
- Show status in status column (currently not working). Should be Pending or Complete
- Add date for next scheduled issuance.

**Comment by stuartf** [comment]
fixed in #83
