### ISSUE TITLE
Needs a page to list existing issuances

### ISSUE THREAD

**Issue by stuartf** [c21u/blockcerts-admin-app#8]
Should list:
 - [x] issuances
 - [x] stats (number of registered users, pending, issued)
 - [x] sign-up url
~~csv upload link~~
 ~~button to close/re-open registration~~

**Comment by mlisle** [comment]
When you select an issuance, you get:

- URL for sign up page that associates user with issuance
- Ability to upload CSV that associates user with issuance

Both would trigger an "Add Issuer" email

**Comment by mlisle** [comment]
If user completes sign up form, they are emailed "Add Issuer" instructions.
If user is included in a CSV uploaded, they are emailed "Add Issuer" instructions.

**Comment by mlisle** [comment]
When ready to issue, select an issuance, see a list of people associated with that issuance (either by signup form or by CSV upload), select people, and click issue.

**Comment by stuartf** [comment]
The work laid out in this issue is all either done or re-designed
