### ISSUE TITLE
Update Readme to include setting up certs

### ISSUE THREAD

**Issue by raymondfx** [c21u/blockcerts-admin-app#82]
Hello,

I ran this program on my local machine as per the instructions on the read.me doc and it seems I can't  access it via my Browser via  https://admin.127.0.0.1.xip.io or   http://0.0.0.0:8000/ even after successfully running the program

System check identified no issues (0 silenced).
web_1          | November 10, 2019 - 08:11:46
web_1          | Django version 2.2.7, using settings 'admin_app.settings'
web_1          | Starting development server at http://0.0.0.0:8000/
web_1          | Quit the server with CONTROL-C.

What could be the Problem?

I Appreciate your feedback.

**Comment by stuartf** [comment]
What error did the browser show when going to https://admin.127.0.0.1.xip.io?

**Comment by raymondfx** [comment]
> What error did the browser show when going to https://admin.127.0.0.1.xip.io?

The page does not display anything
![Uploading Screenshot 2019-11-13 at 13.27.51.png…]
<img width="902" alt="Screenshot 2019-11-13 13 28 35" src="https://user-images.githubusercontent.com/26685061/68755412-81367400-0619-11ea-8b30-7c3413823cef.png">

**Comment by stuartf** [comment]
Oh right, I think the problem is you need to set up trusted certificates for the server and I think we forgot to put that in the readme. You'll want to use https://github.com/FiloSottile/mkcert for MacOS you'd do:

    brew install mkcert
    mkcert -install
    mkdir -p ~/certs
    mkcert -cert-file ~/certs/127.0.0.1.xip.io.crt -key-file ~/certs/127.0.0.1.xip.io.key '*.127.0.0.1.xip.io'

You should only have to do this once as long as you don't delete the ~/certs directory or its contents.

**Comment by raymondfx** [comment]
Yes its working now after trying those steps.

Thanks
